name: Flutter Plugin CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5" # seg a sex, 02:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze_and_test:
    name: Analyze & Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Opcional, mas ajuda em builds Android; para testes/analise não é estritamente necessário.
      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Cache Pub (packages)
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Pub get (root)
        run: flutter pub get

      - name: Pub get (example)
        working-directory: example
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze (strict)
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test

      # Útil para garantir que o package passa nas checagens de publicação
      - name: Dry-run de publicação no Pub
        run: dart pub publish --dry-run

  lint_podspec:
    name: Lint Podspec (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate podspec
        run: pod lib lint ios/braintree_native_ui.podspec --allow-warnings
